services:
  postgres:
    image: postgres:16
    container_name: logistics-ai-copilot-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: logistics_user
      POSTGRES_PASSWORD: logistics_password
      POSTGRES_DB: logistics_ai_copilot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: